export const TOGGLE_LOADING = "TOGGLE_LOADING"
export const HADNLE_ERROR = "HADNLE_ERROR"

export const INCREASE_COUNT = "INCREASE_COUNT"
export const DECREASE_COUNT = "DECREASE_COUNT"
export const CHANGE_VALUE = "CHANGE_VALUE"

export const FETCH_TODOLIST = "FETCH_TODOLIST"
export const FETCH_TODOITEM = "FETCH_TODOITEM"
